apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  dedicated_zm.cfg: |
    {{ .Values.server.config | nindent 4 }}

    map_rotate